Fri Apr 27 20:46:40 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Apr 27 20:46:40 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Apr 27 20:46:41 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Apr 27 20:46:41 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Apr 27 20:46:41 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Apr 27 20:46:41 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Apr 27 20:46:41 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
\т принудительно разорвал существующее подключение', None, 10054, None))
Thu May 17 18:24:10 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Thu May 17 18:24:11 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Thu May 17 18:24:11 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Thu May 17 18:24:11 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Thu May 17 18:24:11 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Thu May 17 18:24:12 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Thu May 17 18:26:07 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot344050353:AAHUwyFQAEDeGaP_5IVqwDn6d_xUJXCfqBo/getUpdates?offset=1&timeout=20 (Caused by ConnectTimeoutError(<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x032A4950>, 'Connection to api.telegram.org timed out. (connect timeout=3.5)'))
Thu May 17 18:26:10 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot344050353:AAHUwyFQAEDeGaP_5IVqwDn6d_xUJXCfqBo/getUpdates?offset=1&timeout=20 (Caused by ConnectTimeoutError(<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x03303C30>, 'Connection to api.telegram.org timed out. (connect timeout=3.5)'))
Thu May 17 18:26:14 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot344050353:AAHUwyFQAEDeGaP_5IVqwDn6d_xUJXCfqBo/getUpdates?offset=1&timeout=20 (Caused by ConnectTimeoutError(<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x033AD470>, 'Connection to api.telegram.org timed out. (connect timeout=3.5)'))
Thu May 17 18:26:27 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Thu May 17 18:26:27 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:10:53 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:10:53 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:10:53 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:10:53 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:10:53 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:10:53 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:10:53 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:10:54 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:10:54 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:10:54 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:10:54 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:10:54 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:10:54 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:10:54 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:10:54 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:10:54 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:10:54 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:10:55 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:10:55 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:10:55 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:10:55 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:10:55 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:10:55 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:10:55 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:10:55 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:10:55 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:10:55 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:10:56 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:10:56 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:10:56 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:10:56 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:10:56 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:10:56 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:10:56 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:10:56 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:10:56 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:10:57 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:10:57 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:10:57 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:10:57 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:10:57 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:10:57 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:10:57 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:10:58 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:55 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:56 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:57 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:58 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:59 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:59 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:59 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:59 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:59 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:59 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:59 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:59 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:59 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:59 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:59 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:59 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:59 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:17:59 2018Missing dependencies for SOCKS support.
Fri Nov  9 20:20:56 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021325204390>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:56 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213252C6048>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:56 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213252C6D68>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:56 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213252D1B38>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:56 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213252DF908>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:56 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213252E86D8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:56 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213252F6438>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213252FF198>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213252FFF28>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021325310CF8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000002132531AAC8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021325324898>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021325332668>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000002132533A438>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021325348208>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021325353048>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021325353D68>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021325363B38>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000002132536D908>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213253786D8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213253814A8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000002132538D278>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021325399048>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021325399DD8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213253A7BA8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213253B5978>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213253BC748>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213253CC518>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213253D22E8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213253E20B8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213253E2E48>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213253EEC18>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213253FB9E8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213254077B8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021325411588>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000002132541B358>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021325427128>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021325427EB8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021325434C88>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021325443A58>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000002132544E828>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000002132545A5F8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213254653C8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021325470198>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021325470F28>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000002132547BCF8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021325485AC8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021325594898>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000002132559D668>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213255AC438>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213255B7208>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213255C0048>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213255C0D68>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213255CDB38>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213255DA908>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213255E66D8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213255F04A8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213255FD278>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021325609048>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021325609DD8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021325612BA8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021325621978>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000002132562B748>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021325638518>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213256412E8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000002132564F0B8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000002132564FE48>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000002132565AC18>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000002132566A9E8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213256767B8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000002132567D588>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000002132568C358>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021325698128>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021325698EB8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213256A3C88>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213256B2A58>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213256BD828>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213256C65F8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213256D13C8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213256DE198>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213256DEF28>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213256E9CF8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213256F5AC8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021325703898>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000002132570F668>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021325717438>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021325724208>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021325730048>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021325730D68>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000002132573EB38>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000002132574C908>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213257546D8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213257614A8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000002132576C278>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021325776048>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021325776DD8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021325783BA8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000002132578E978>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000002132579A748>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213257A6518>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213257B02E8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213257BC0B8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213257BCE48>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213257C8C18>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021325FD79E8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021325FE27B8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021325FE9588>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021325FF8358>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021326002128>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021326002EB8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000002132600FC88>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:57 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000002132601DA58>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021326028828>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213260355F8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213260413C8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000002132604A198>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000002132604AF28>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021326055CF8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021326062AC8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000002132606E898>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021326076668>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021326084438>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021326093208>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000002132609C048>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000002132609CD68>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213260A9B38>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213260B6908>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213260C06D8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213260CC4A8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213260D8278>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213260E2048>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213260E2DD8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213260F0BA8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213260FD978>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021326107748>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021326111518>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000002132611F2E8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000002132612B0B8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000002132612BE48>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021326138C18>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213261459E8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000002132614D7B8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000002132615A588>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021326166358>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021326171128>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021326171EB8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000002132617EC88>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000002132618CA58>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021326194828>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000002132619E5F8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213261AD3C8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213261B9198>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213261B9F28>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213261C5CF8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213261D3AC8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213261DF898>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213261E5668>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213261F4438>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021326200208>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000002132620A048>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000002132620AD68>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021326216B38>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021326226908>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213262316D8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213262354A8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021326243278>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021326252048>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021326252DD8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021326260BA8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000002132626C978>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021326276748>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021326282518>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000002132628C2E8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213262990B8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021326299E48>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213262A6C18>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213262B49E8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213262BC7B8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213262C7588>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213262D1358>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213262DE128>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213262DEEB8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213262EAC88>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213262FAA58>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021326304828>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213263115F8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000002132631A3C8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021326325198>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021326325F28>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021326333CF8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000002132633CAC8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000002132634B898>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021326355668>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021326362438>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000002132636A208>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021326372048>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021326372D68>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021326387B38>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000002132638F908>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000002132639D6D8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213263A34A8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213263B3278>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213263BF048>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213263BFDD8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:58 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213263CBBA8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:59 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213263D9978>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:59 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213263E0748>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:59 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213263EE518>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:59 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213263F52E8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:59 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213264050B8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:59 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021326405E48>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:59 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021326413C18>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:59 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213264209E8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:59 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213264297B8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:59 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021326434588>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:59 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021326442358>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:59 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000002132644E128>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:59 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000002132644EEB8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:59 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000002132645BC88>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:59 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021326469A58>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:59 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021326473828>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:59 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000002132647D5F8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:59 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213264883C8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:59 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021326492198>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:59 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0000021326492F28>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:59 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213264A0CF8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:20:59 2018SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot534475499:AAEFogOl9_XV1BuRKavjLK6jqciDzh-lIqQ/getUpdates?offset=1&timeout=20 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x00000213264ACAC8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Fri Nov  9 20:31:11 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:11 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:11 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:11 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:11 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:11 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:11 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:11 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:11 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:11 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:12 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:12 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:12 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:12 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:12 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:12 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:13 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:13 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:13 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:14 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:14 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:14 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:14 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:14 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:14 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:15 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:15 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:15 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:15 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:15 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:15 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:15 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:16 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:16 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:16 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:16 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:16 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:16 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:16 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:16 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:16 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:16 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:16 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:17 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:17 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:17 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:17 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:17 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:17 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:17 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:17 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:17 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:17 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:17 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:18 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:18 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:18 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:18 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:18 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:18 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:18 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:18 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:18 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:18 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:19 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:19 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:19 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:19 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 20:31:19 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:23:19 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:23:19 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:23:20 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:23:20 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:23:20 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:23:20 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:23:20 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:23:20 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:23:20 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:23:20 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:23:20 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:23:21 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:23:21 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:23:21 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:23:21 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:23:21 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:23:21 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:23:21 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:23:21 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:23:22 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:23:22 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:23:22 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:23:22 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:23:22 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:23:22 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:23:22 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:23:22 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:23:23 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:23:23 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:23:23 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:23:23 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:23:23 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:23:23 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:23:23 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:23:23 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:23:23 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:23:24 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:23:24 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:23:24 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:23:24 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:23:24 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:23:24 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:23:24 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:23:24 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:23:24 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:23:25 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:23:25 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:23:25 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:23:25 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:23:25 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:23:25 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:23:25 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:23:25 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:23:25 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:23:26 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:23:26 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:23:26 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:23:26 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:23:26 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:35 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:35 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:35 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:35 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:35 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:35 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:35 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:36 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:36 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:36 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:36 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:36 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:36 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:36 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:37 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:37 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:37 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:37 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:37 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:37 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:37 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:38 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:38 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:38 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:38 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:38 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:38 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:38 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:39 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:39 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:39 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:39 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:39 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:39 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:39 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:49 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:49 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:49 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:49 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:49 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:49 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:49 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:49 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:50 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:50 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:50 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:50 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:50 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:50 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:50 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:50 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:51 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:51 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:51 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:51 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:51 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:51 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:51 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:51 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:52 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:52 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:52 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:52 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:52 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:52 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:52 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:52 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:53 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:53 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:53 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:53 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:53 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:53 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:53 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:53 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:54 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:54 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:54 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:54 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:54 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:54 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:54 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:54 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:55 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:55 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:55 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:55 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:55 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:55 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
Fri Nov  9 21:26:55 2018('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
